dist: bionic
services:
- docker
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  # - DOCKER_BUILDKIT=1
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - REPO_NAME=reset-touch
  - REPO_USER=flipdot
  - secure: tnjXAgl5ArvWBluAjumeylItx3C4p6npTkS/Nt9/XUWbz1jaD1axrGfStXQr4/fIrsNPcLMxjQWO4jgh2skJNVunztt9vrP8wUbhEYAo6+jWAmywGH1gWOyoItO5CMF7M3JjefsFwwi548YUJav/FS9+OQyfqybl8nujAL49Swy+fVvSOwAXNBCIMnpANQORAiNOODMasHf44RAY6uOyg2cBoTxPTmecu2zwFp+5stkiZGIzR94zEJnlpwD1iIwPHeY0Dftd+/SnmD7oqvqvQHKzLyERjpZ8pVDAvAiB8DjZrLCbMuJOeTbJDWdpQJmvSQvTnG+GmhBMESNKdYaPv9OWJZ2I1wo2cTfQxOfeVJWVsYkKJk8yaNWaRVeJHmN8ZYnGEAxZWLRsCPA8/g0D1PBI22Oj8p+JE9c/PIw/l8zpxpZVqCESg4eq/80xtgBeaTd2jIcbsTej3FSdMSU+W1Qx1pfnVex+ytc23rzHG5Ue/G+YIzONBKdlZV3KHntjbxjM600VFTp1MODqBGPyflyKpdV2AnUqyZwr9BQ0nuGWn8M4xSP/baiwy/8J4t/XpT5S2qjZjr12pvMdBc7YswAjAVJUT9lHTq9E2K+3yBQmn9xlU+fGhXVprLtt4RzYERGltUft6znfYZJ3kDNrHCDfM3XGp6WDkMVFTYhShzA= #DOCKER_USER
  - secure: o5jmGGqbPbVWumRB08seardb25ZvdPrgnEIicisprx8sXWlBnelO7ILHk2rfszVjylVrUiCeUqet8mVNK1Ev05ARe86lNghIdyixPaqbPF4sI8WgQdh3z4PBN+AEt9H77Kkkv01PeSJz7DKtyone3kKXHf5VH0Y+1PrZCqHqMEV6z4eRmmDz+loWRuaLnU1ohow/duWo4rNuR3OT9nz+n26AdlOVMOUahVxV3OjuADxu+uZtQLxaCe0PYFvtPlX5dUfqLlDP8VJEnNcegocKbPUqOXjiHP8S/A421lgoiK/KVkFCB+WerJ9wxe2xcSqSgb4qCHsoOkWiyC/LqnXWPa/WjEeHtEBuj0f77CG1l9DDqWAiSIp7hOhiQFLwoIhSw6kr9AIkYutAVarLset5nTl7oVnZxf90UQ5PdG6kaPc7Zd9EFPJWF9Hb4N3uz/lmnX1dIXgB6TGWSUOKKuSsG7bF9R3+WMYu6Ioy9HkIShHau8NsaAm2pR/kPSq/mGC6/QF+1ngOvnWw5Uy2h0v0AaW8yDqnZ8WJ7phwksQeNtoFJJabr1FJJc798DxfAsEkTOmgpll832TEXeP7DhP22ulP6pKo7aQTjuqMQu4Gdf6o21SUQXOcCNs6c89BAwLpunpPmu3ULNT8UMKKbFNLh311tqgkL52gqgWZmnGPOtw= #DOCKER_PASS
before_install:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $(echo $TRAVIS_BRANCH | tr / _); fi`
- |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update
    sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- |
    docker run --rm --privileged docker/binfmt:820fdd95a9972a5308930a2bdfb8573dd4447ad3
    docker buildx create --name travis-builder --use
    docker buildx inspect --bootstrap
script:
- docker buildx build --cache-from=$REPO_USER/$REPO_NAME:cache --cache-to=$REPO_USER/$REPO_NAME:cache --platform linux/amd64,linux/arm/v7 --push -t $REPO_USER/$REPO_NAME:$COMMIT -t $REPO_USER/$REPO_NAME:$TAG $PWD
